import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
// import Gamecard from '../components/Gamecard/gamecard.js'
import Header from '../components/Header/Header'
import Homebody from '../components/HomeBody/homebody'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
        <Header></Header>
        <Homebody></Homebody>
        {/* <Gamecard/> */}
        </div>
      </main>
    </>
  )
}
