import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import HomePage from "../components/HomePage/HomePage";
//import Login from "../components/Login/Login";
import Profile from "../components/Profile/Profile";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Stokka</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,0"
        />
      </Head>
      <main className={styles.main}>
        <div className={styles.cardComponentSection}>
          <div>
            <Header></Header>

            <HomePage></HomePage>
          </div>
        </div>
      </main>
    </>
  );
}
