
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header'
import HomePage from '../components/HomePage/HomePage'
import Login from '../components/Login/Login'
import Logout from '../components/logout/Logout'


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Stokka</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.cardComponentSection}>
        <div>
        <Header></Header>
        <Login/>
        <Logout/>
        <HomePage></HomePage>
        </div>
        </div>
      </main>
    </>
  )

}
